### ISSUE TITLE
New payments, does not hold a date change

### ISSUE THREAD

**Issue by MargaretLangley** [BCS-io/letting#219]
Go to New payment
Search for 6237
Change date to a January date
Put in suitable payment
Submit payment

Go to accounts menu 
Search for 6237
Check date on payments

**Comment by MargaretLangley** [comment]
Testing has confirmed that this is now fixed

**Comment by RichardWigley** [comment]
Fixed in version 0.0.50   commit: dbb02c364d11bdb77c706fa755ef8854aafafb17
