### ISSUE TITLE
New Invoicing, invoice date should remain set for new run of invoices 

### ISSUE THREAD

**Issue by MargaretLangley** [BCS-io/letting#221]
Go to New Invoicing
Set property Range to  6331-6333
Set Invoice Date to 1st April
Create Invoices

The page comes back with message confirming invoices created 
The Invoice Date has reverted to today's date

**Comment by RichardWigley** [comment]
Fix    8e96ea27833eeba3ec8f79c2efa0f1bf99ff1c3e
Version Released as 0.0.51

**Comment by MargaretLangley** [comment]
Tested and seems fine
