### ISSUE TITLE
New Payments date is set at last payment date

### ISSUE THREAD

**Issue by MargaretLangley** [BCS-io/letting#228]
Although the payment date should remain the same when a bunch of payments are made, perhaps the first time payments are made in the day the payment date should be today's date.

**Comment by RichardWigley** [comment]
Payment date is kept in a session variable, which is by default today's date, but can be changed to whatever date the user desires.

The session variable will remember the set date until the browser has been shutdown. The next time the browser is opened and the user logs into the site the browser will again initialize the date to today date.

Keeping the browser open overnight, or saving the state of the machine with the browser open, will result in saving the session's date from the previous day.

Note: This program saves the sessions in cookies, the default way - this will affect the options for clearing the session.
