### ISSUE TITLE
Account Charges Due Dates over written in Edit

### ISSUE THREAD

**Issue by MargaretLangley** [BCS-io/letting#243]
View account 6893 (or similar number, account with more than 1 set of due dates).
Check due dates one is a Ground rent, one a monthly service charge.
Use the Edit icon to go to Edit.
The charge dates have been overwritten by the top due date.
If you go back to View the true dates are shown.
If you save the edit the overwritten date is saved. Can go back to view to see this.

**Comment by RichardWigley** [comment]
Dates Due were not being initialised to the current value - so when editing an account's charge the charge's dates due were left as the first drop down row and not the actual value.

We use 'grouped_options_for_select' and it  expects you to pass the selected item as the second parameter. http://apidock.com/rails/v4.1.8/ActionView/Helpers/FormOptionsHelper/grouped_options_for_select

When this is done the charge's due_date is correctly initialised.

**Comment by MargaretLangley** [comment]
Checked 6138 on view. Details on Edit were the same. Changing data: name, manual, domant, due dates and updating, the data was handled successfully. A midterm charge was used. The view gave this as Arrears.
