### ISSUE TITLE
Creating a New Account, incorrect data in charging on submit, overwrites charging due dates  

### ISSUE THREAD

**Issue by MargaretLangley** [BCS-io/letting#244]
Start creating a new account. Create more than 1 charge,  miss off the amount for 1 charge.
Submit.
Error message + the charge dates all set to the first charge due date on the charge list

**Comment by RichardWigley** [comment]
Fix added in  cb35e50c6e48c89c1937f7fb03831fbab8883e2b
Mainly tidying the complicated code and adding in more tests - the actual fix is in the reveal helper going from record.new? to record.empty?

**Comment by MargaretLangley** [comment]
Test seems Ok
