### ISSUE TITLE
Garage Ground Rent on 2nd page of Invoice not Garage Ground Rent

### ISSUE THREAD

**Issue by MargaretLangley** [BCS-io/letting#250]
The second page of an invoice is required for accounts with ground rents or garage ground rents

There are 2 types of rentable invoices:
1) Accounts containing Ground Rent and Garage Ground Rent - in this case the second page should contain only the Ground Rent (which is much larger).

Bug
i) New Invoicing
ii) Property Range set to:  6331-6333
iii) Create Invoice - notice that it has a Ground Rent and a Garage Ground Rent
iv) Print out invoice 6331 - notice that it has only the Garage Ground Rent - when we expect Ground Rent.

2) Some accounts have been broken up and one account contains the Ground Rent and the other the Garage ground rent. When this happens you print out the Ground Rent and Garage Ground Rent on the second page as appropriate.  

(give example - I am trying to understand what I'm missing here? Why is it a problem? Surely they are two separate accounts? Are they kept in the same account? )

**Comment by RichardWigley** [comment]
Tests were passing, however, the sort wasn't working on the live system. Removed a default ordering on products and everything worked. Fix includes another problem of ordering the products by date and then charge_type.
Fix  4da8c34c7e2b9e8a5fa694d5236d431fa6c08622

**Comment by MargaretLangley** [comment]
Tested ok
