### ISSUE TITLE
Confirm printing experience on Linux is the same as Windows

### ISSUE THREAD

**Issue by RichardWigley** [BCS-io/letting#258]
Want to know that printing is straightforward on Linux as Windows- Want to see 1 dialog box with print as default option. 

1) Close down the browser.
2) Open the browser and go to the website. Print out a page and see that it remembers the printing options so that all the user has to do is select 'Print' on the browser print dialog.

This should be enough. However, consider rebooting machine in a manner that it cannot possibly remember state and redo the above steps.

Report back to purchasing

**Comment by RichardWigley** [comment]
Closing and Opening the browser you still see
1) The expected default printer
2) Duplex printing as expected.

Not rebooted.

**Comment by MargaretLangley** [comment]
Have started my system from switch off and the browser print options keep the 2-sided and no header/footer instructions ok.

**Comment by RichardWigley** [comment]
Everything was remembered between closing browser or rebooting the box with the browser closed.
