### ISSUE TITLE
Client Payment - add date range to the detail page

### ISSUE THREAD

**Issue by RichardWigley** [BCS-io/letting#260]
Client View - Payments  -> Detailed Payment
Display the range of dates that the payments were accumulated over.

**Comment by MargaretLangley** [comment]
Also needs the client id /name

**Comment by RichardWigley** [comment]
Added the client id / name to staging server. Not figured how to do the date range.

**Comment by MargaretLangley** [comment]
Checked out client id / name to staging server. That's OK

**Comment by RichardWigley** [comment]
Date range for collection added 1215251d22bc1fbbebfaa6be6b40ddf9bf3b72d3

**Comment by MargaretLangley** [comment]
Change to finish on the last day of month OK. Everything checked out
