### ISSUE TITLE
Not possible to return to 1st invoices once the 2nd invoices are created

### ISSUE THREAD

**Issue by MargaretLangley** [BCS-io/letting#267]
Set up some new invoices - include ones with Ground Rent (>6000)
Check that new invoices' printouts are ok
Go to Blue invoices, create the 2nd invoices.
Once the tab is up for 2nd invoices the 1st ones don't print out their 2nd leasehold page

**Comment by RichardWigley** [comment]
FIX e54b1ae12b4eb722c688da2cdb8b86502e19dca7

**Comment by MargaretLangley** [comment]
Fix seems ok. Have been able to print both sets of invoices.
