### ISSUE TITLE
Single hyphen in entity's title

### ISSUE THREAD

**Issue by RichardWigley** [BCS-io/letting#280]
Some records have a title which is set to the char '-'  we want this removed. 

The affected records are:  1401,  2114,   2258,   2745,  6122,   6193,  6209,  6224

**Comment by MargaretLangley** [comment]
The hyphens appear programmatically. Looking at the data in the old program there is no hypthen. 
They only appear when there are initials but no title. Names which have no initial and no title remain blank.

**Comment by RichardWigley** [comment]
Fix 960251ac5491fe5f0b9f15cebefb829b398c8517
