### ISSUE TITLE
New Account's Client id cannot be entered into the text box.

### ISSUE THREAD

**Issue by MargaretLangley** [BCS-io/letting#309]
### Creating a new account's client id

Entering a new account by changing the text box allows you to make the change but the value does not register. It only works when you select the client (highlighting the choice and pressing return).

#### Error
Creating an account. 
Navigate to: accounts/new
  - Fill in a new account and give the client id of 16.
  - save account
    - save fails

#### Expect

By entering 16 as text the client id should be updated to 16

**Comment by MargaretLangley** [comment]
> No description provided.

eating

**Comment by RichardWigley** [comment]
Client ID text box uses autocomplete. Autocomplete it is useful when you need to create something new as well as be able to select something already on the system. This is not the case with clients - we don't need to create a new client while on the accounts new page. Consequently, we can change this to a plain dropdown select box - avoiding the problem.
